# Generated by Django 3.0.7 on 2020-06-19 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 6, 19, 19, 11, 40, 165003, tzinfo=utc)),
        ),
    ]
