# Generated by Django 3.0.7 on 2020-06-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200623_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={'ordering': ['-date', 'city']},
        ),
        migrations.AlterField(
            model_name='user_post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.City'),
        ),
    ]
