# Generated by Django 3.0.7 on 2020-06-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_post',
            old_name='author',
            new_name='user',
        ),
    ]
