# Generated by Django 3.0.7 on 2020-06-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_post',
            options={},
        ),
        migrations.AlterField(
            model_name='user_post',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.City'),
        ),
    ]
