# Generated by Django 3.0.7 on 2020-06-23 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200623_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
    ]
