# Generated by Django 3.0.7 on 2020-06-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200623_0958'),
        ('main_app', '0005_auto_20200623_0508'),
    ]

    operations = [
    ]
